/*
* This Java source file was generated by the Gradle 'init' task.
*/
package seleniumjava;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

public class App {
    public static void main(String[] args) {
        System.out.println(running());
        SeleniumDemo1();
        SeleniumDemo2();
    }
    public static String running() {
        return "Hello World!";
    }  
    public static void SeleniumDemo1() {
        // Set the path to the geckodriver executable
        System.setProperty("webdriver.edge.driver", "WebDrivers/msedgedriver.exe");

        // Create a new Firefox WebDriver instance
        WebDriver driver = new EdgeDriver();
        
        //Maximize window      
        driver.manage().window().maximize();    

        driver.get("https://www.google.com/");
        assert driver.getTitle() == "Google";

        // Open Google and locate Search Box
        WebElement searchBox = driver.findElement(By.name("q"));

        // Enter the search query "Birds"
        searchBox.sendKeys("Birds");

        // Submit the search query
        searchBox.submit();

        assert driver.findElement(By.xpath("Wikipedia")).isSelected();  
        // Wait for the search results to load
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        // Close the browser
        driver.quit();
    }

    public static void SeleniumDemo2() {
        // Set the path to the geckodriver executable
        System.setProperty("webdriver.edge.driver", "WebDrivers/msedgedriver.exe");

        // Create a new Firefox WebDriver instance
        WebDriver driver = new EdgeDriver();

        //Maximize window      
        driver.manage().window().maximize();    

        //Launch the Site.      
        driver.get("https://www.lambdatest.com/selenium-playground/simple-form-demo");
        assert driver.getTitle().contains("Selenium Grid Online");

        // Wait for the website to load
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        //Enter values into form and submit      
        driver.findElement(By.id("sum1")).sendKeys("2");                    
        driver.findElement(By.id("sum2")).sendKeys("2");    
        driver.findElement(By.xpath("//*[@id='gettotal']/button")).click();  

        // Wait for the website to load
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        //Verify the result
        String result = driver.findElement(By.xpath("//*[@id=\'addmessage\']")).getText();

        if( Integer.parseInt(result) == 4) {
            System.out.println("2+2 = 4");
        } else {
            System.out.println("2+2 != 4");
        }
        // Wait before closing
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.quit(); 
    }
    
}
